import os

out = r"C:\Users\akash\OneDrive\Documents\hyperlocal_customer_app\apps/shopkeeper_app\lib\features\shops\presentation\screens\shop_register_screen.dart"

L = []
a = L.append

a("import 'package:flutter/material.dart';")
a("import 'package:flutter_riverpod/flutter_riverpod.dart';")
a("import 'package:google_maps_flutter/google_maps_flutter.dart';")
a("import '../../data/location_service.dart';")
a("import '../../data/pincode_lookup.dart';")
a("import '../../data/pincode_api_service.dart';")
a("import '../../data/gstin_decoder.dart';")
a("import '../../domain/shop_models.dart';")
a("import '../controllers/shops_controller.dart';")
a("import 'map_picker_screen.dart';")
a("")
a("class ShopRegisterScreen extends ConsumerStatefulWidget {")
a("  const ShopRegisterScreen({super.key});")
a("  @override ConsumerState<ShopRegisterScreen> createState() => _ShopRegisterScreenState();")
a("}")
a("")
a("class _ShopRegisterScreenState extends ConsumerState<ShopRegisterScreen> {")
a("  final _formKey = GlobalKey<FormState>();")
a("  final _name = TextEditingController();")
a("  final _tagline = TextEditingController();")
a("  final _description = TextEditingController();")
a("  final _phone = TextEditingController();")
a("  final _gstin = TextEditingController();")
a("  final _addressLine = TextEditingController();")
a("  final _city = TextEditingController();")
a("  final _state = TextEditingController();")
a("  final _pincode = TextEditingController();")
a("  String _category = 'GROCERY';")
a("  bool _pinLoading = false;")
a("  bool _locating = false;")
a("  LatLng? _coordinates;")
a("  String? _detectedAddress;")
a("  GstinDetails? _gstinDetails;")
a("  PincodeApiResult? _pincodeResult;")
a("")
a("  @override void initState() {")
a("    super.initState();")
a("    _pincode.addListener(_onPincode);")
a("    _gstin.addListener(_onGstin);")
a("    PincodeLookup.instance.ensureLoaded();")
a("  }")
a("")
a("  @override void dispose() {")
a("    _pincode.removeListener(_onPincode);")
a("    _gstin.removeListener(_onGstin);")
a("    for (final c in [_name,_tagline,_description,_phone,_gstin,_addressLine,_city,_state,_pincode]) { c.dispose(); }")
a("    super.dispose();")
a("  }")
a("")
a("  void _onPincode() {")
a("    final code = _pincode.text.trim();")
a("    if (code.length != 6) { setState(() => _pincodeResult = null); return; }")
a("    final local = PincodeLookup.instance.lookupSync(code);")
a("    if (local != null) {")
a("      if (_city.text.trim().isEmpty) _city.text = local.city;")
a("      if (_state.text.trim().isEmpty) _state.text = local.state;")
a("    }")
a("    _lookupPincodeApi(code);")
a("  }")
a("")
a("  Future<void> _lookupPincodeApi(String code) async {")
a("    setState(() => _pinLoading = true);")
a("    try {")
a("      final result = await PincodeApiService.instance.lookup(code);")
a("      if (!mounted || result == null) return;")
a("      setState(() {")
a("        _pincodeResult = result;")
a("        if (_city.text.trim().isEmpty) _city.text = result.city;")
a("        if (_state.text.trim().isEmpty) _state.text = result.state;")
a("        if (_addressLine.text.trim().isEmpty && result.postOffices.isNotEmpty) {")
a("          _addressLine.text = result.postOffices.first.name;")
a("        }")
a("      });")
a("    } catch (_) {} finally { if (mounted) setState(() => _pinLoading = false); }")

L2 = []
b = L2.append

b("  Future<void> _pickOnMap() async {")
b("    final result = await Navigator.of(context).push<PickedLocation>(MaterialPageRoute(builder: (_) => MapPickerScreen(initialLocation: _coordinates)));")
b("    if (result != null && mounted) {")
b("      setState(() {")
b("        _coordinates = LatLng(result.latitude, result.longitude);")
b("        _detectedAddress = result.addressLine;")
b("        if (result.addressLine != null && result.addressLine!.isNotEmpty && _addressLine.text.trim().isEmpty) _addressLine.text = result.addressLine!;")
b("        if (result.city != null && result.city!.isNotEmpty && _city.text.trim().isEmpty) _city.text = result.city!;")
b("        if (result.state != null && result.state!.isNotEmpty && _state.text.trim().isEmpty) _state.text = result.state!;")
b("        if (result.pincode != null && result.pincode!.isNotEmpty && _pincode.text.trim().isEmpty) _pincode.text = result.pincode!;")
b("      });")
b("    }")
b("  }")
b("")
b("  Future<void> _submit() async {")
b("    if (!_formKey.currentState!.validate()) return;")
b("    FocusScope.of(context).unfocus();")

L3 = []
c = L3.append
c("  @override Widget build(BuildContext context) {")
c("    final s = ref.watch(shopsControllerProvider.select((st) => st.status == ShopsStatus.loading));")
c("    return Scaffold(appBar: AppBar(title: const Text('Register a new shop')), body: SafeArea(child: Form(key: _formKey, child: ListView(padding: const EdgeInsets.all(16), children: _buildFormFields(s)))));")
c("  }")
c("")
c("  List<Widget> _buildFormFields(bool s) => [")
c("    Text('Business details', style: Theme.of(context).textTheme.titleMedium), gap(12),")
c("    field(_name, 'Shop name *', capitalization: TextCapitalization.words), gap(12),")
c("    DropdownButtonFormField<String>(initialValue: _category, decoration: const InputDecoration(labelText: 'Category *'), items: [for (final cat in kShopCategories) DropdownMenuItem(value: cat, child: Text(cat))], onChanged: (v) => setState(() => _category = v ?? _category)), gap(12),")
c("    field(_tagline, 'Tagline (optional)', hint: 'e.g. Fresh groceries'), gap(12),")
c("    TextFormField(controller: _description, maxLines: 3, decoration: const InputDecoration(labelText: 'Description (optional)')), gap(12),")
c("    field(_phone, 'Business phone (optional)', prefix: '+91 ', hint: '9999999999', keyboard: TextInputType.phone), gap(12),")
c("    field(_gstin, 'GSTIN (optional)', hint: '22AAAAA0000A1Z5', capitalization: TextCapitalization.characters),")
c("    if (_gstinDetails != null && _gstinDetails!.isValid) ...[gap(8), _gstinCard(_gstinDetails!)], gap(24),")
c("    Text('Location & address', style: Theme.of(context).textTheme.titleMedium), gap(12),")
c("    Row(children: [Expanded(child: ElevatedButton.icon(onPressed: _locating ? null : _detectLocation, icon: _locating ? spin() : const Icon(Icons.my_location), label: Text(_locating ? 'Detecting...' : 'Detect my location'), style: ElevatedButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 14))), gapw(12),")
c("      Expanded(child: OutlinedButton.icon(onPressed: _pickOnMap, icon: const Icon(Icons.map), label: const Text('Pick on map'), style: OutlinedButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 14)))]),")
c("    if (_coordinates != null) ...[gap(8), _liveCoordinatesCard()], gap(12),")
c("    field(_addressLine, 'Address line *', capitalization: TextCapitalization.words), gap(12),")
c("    Row(children: [Expanded(child: field(_city, 'City *')), gapw(12), Expanded(child: field(_state, 'State *')), gapw(12),")
c("      Expanded(child: TextFormField(controller: _pincode, keyboardType: TextInputType.number, maxLength: 6, decoration: InputDecoration(labelText: 'Pincode *', counterText: '', suffixIcon: _pinLoading ? spin() : (_pincodeResult != null ? const Icon(Icons.check_circle, color: Colors.green) : null)), validator: (v) => (v ?? '').trim().length != 3 ? 'Required' : null))]),")
c("    if (_pincodeResult != null) ...[gap(8), _pincodeResultCard()], gap(24),")

L4 = []
d = L4.append
d("  Widget _liveCoordinatesCard() => Container(width: double.infinity, padding: const EdgeInsets.all(10),")
d("    decoration: BoxDecoration(color: Colors.blue.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(8), border: Border.all(color: Colors.blue.withValues(alpha: 0.3))),")
d("    child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
d("      const Text('Live Coordinates', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 12)), const SizedBox(height: 2),")
d("      Text('Lat: ${_coordinates!.latitude.toStringAsFixed(6)}  Lng: ${_coordinates!.longitude.toStringAsFixed(6)}', style: const TextStyle(fontFamily: 'monospace', fontSize: 13)),")
d("    ]));")
d("")
d("  Widget _pincodeResultCard() { final r = _pincodeResult!; return Container(width: double.infinity, padding: const EdgeInsets.all(10),")
d("    decoration: BoxDecoration(color: Colors.green.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(8), border: Border.all(color: Colors.green.withValues(alpha: 0.3))),")
d("    child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
d("      Text('Pincode: ${r.pincode}', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 12)), const SizedBox(height: 2),")
d("      if (r.city.isNotEmpty) Text('City: ${r.city}', style: const TextStyle(fontSize: 13)),")
d("      if (r.district.isNotEmpty) Text('District: ${r.district}', style: const TextStyle(fontSize: 13)),")
d("      Text('State: ${r.state}', style: const TextStyle(fontSize: 13)),")
d("    ])); }")
d("")
d("  Widget field(TextEditingController ctl, String label, {String? hint, String? prefix, TextInputType? keyboard, TextCapitalization capitalization = TextCapitalization.none}) =>")
d("    TextFormField(controller: ctl, keyboardType: keyboard, textCapitalization: capitalization, decoration: InputDecoration(labelText: label, hintText: hint, prefixText: prefix), validator: (v) => label.endsWith('*') && (v ?? '').trim().isEmpty ? 'Required' : null);")
d("")
d("  Widget gap(double h) => SizedBox(height: h);")
d("  Widget gapw(double w) => SizedBox(width: w);")
d("  Widget spin() => const Padding(padding: EdgeInsets.all(12), child: SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2)));")
d("")
d("  Widget _gstinCard(GstinDetails d) => Container(width: double.infinity, padding: const EdgeInsets.all(12),")
d("    decoration: BoxDecoration(color: Theme.of(context).colorScheme.secondaryContainer.withValues(alpha: 0.5), borderRadius: BorderRadius.circular(8), border: Border.all(color: Theme.of(context).colorScheme.secondary.withValues(alpha: 0.4))),")
d("    child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
d("      Text('GSTIN Owner Details', style: Theme.of(context).textTheme.titleSmall), const SizedBox(height: 4),")
d("      Text('State: ${d.stateName ?? '-'} (Code: ${d.stateCode ?? '-'})'), Text('Owner PAN: ${d.pan ?? '-'}'), Text('Entity: ${d.entityName ?? '-'}'),")
d("    ]));")
d("}")

with open(out, 'a', encoding='utf-8') as f:
    f.write('\n'.join(L4))

print("ALL DONE")

c("    FilledButton.icon(onPressed: s ? null : _submit, icon: s ? spin() : const Icon(Icons.storefront), label: const Text('Register shop')), gap(32),];")
c("")

with open(out, 'a', encoding='utf-8') as f:
    f.write('\n'.join(L3))

print("PART3 DONE")

b("    final payload = <String, dynamic>{'name': _name.text.trim(), 'category': _category, if (_tagline.text.trim().isNotEmpty) 'tagline': _tagline.text.trim(), if (_description.text.trim().isNotEmpty) 'description': _description.text.trim(), if (_phone.text.trim().isNotEmpty) 'phone': _phone.text.trim(), if (_gstin.text.trim().isNotEmpty) 'gstin': _gstin.text.trim(), 'latitude': _coordinates?.latitude ?? 0.0, 'longitude': _coordinates?.longitude ?? 0.0, 'address': {'address_line1': _addressLine.text.trim(), 'city': _city.text.trim(), 'state': _state.text.trim(), 'pincode': _pincode.text.trim()}};")
b("    final ok = await showDialog<bool>(context: context, builder: (_) => _confirmDialog(payload));")
b("    if (ok != true) return;")
b("    final done = await ref.read(shopsControllerProvider.notifier).registerShop(payload);")
b("    if (!mounted) return;")
b("    if (done) { context.go('/dashboard'); } else { ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(ref.read(shopsControllerProvider).errorMessage ?? 'Registration failed'))); }")
b("  }")
b("")
b("  AlertDialog _confirmDialog(Map<String, dynamic> p) {")
b("    final a = p['address'] as Map<String, dynamic>;")
b("    Widget row(String k, String? v) => Padding(padding: const EdgeInsets.symmetric(vertical: 2), child: Row(children: [SizedBox(width: 90, child: Text('$k:', style: const TextStyle(fontWeight: FontWeight.bold))), Expanded(child: Text((v != null && v.isNotEmpty) ? v : '-'))]));")
b("    return AlertDialog(title: const Text('Confirm shop details'), content: SingleChildScrollView(child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [row('Shop name', p['name']), row('Category', p['category']), if (p['tagline'] != null) row('Tagline', p['tagline']), if (p['phone'] != null) row('Phone', p['phone']), if (p['gstin'] != null) row('GSTIN', p['gstin']), const Divider(), row('Address', a['address_line1']), row('City', a['city']), row('State', a['state']), row('Pincode', a['pincode']), const Divider(), row('Latitude', (p['latitude'] as double).toStringAsFixed(6)), row('Longitude', (p['longitude'] as double).toStringAsFixed(6))])), actions: [TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('Close')), FilledButton(onPressed: () => Navigator.pop(context, true), child: const Text('Register'))]);")
b("  }")
b("")

with open(out, 'a', encoding='utf-8') as f:
    f.write('\n'.join(L2))

print("PART2 DONE")

a("  }")
a("")
a("  void _onGstin() {")
a("    final raw = _gstin.text.trim();")
a("    setState(() => _gstinDetails = raw.length == 15 ? GstinDecoder.instance.decode(raw) : null);")
a("  }")
a("")
a("  Future<void> _detectLocation() async {")
a("    setState(() => _locating = true);")
a("    try {")
a("      final r = await LocationService.instance.detectCurrentLocation();")
a("      if (!mounted) return;")
a("      setState(() {")
a("        _coordinates = LatLng(r.latitude, r.longitude);")
a("        _detectedAddress = r.addressLine;")
a("        if (r.addressLine != null && r.addressLine!.isNotEmpty && _addressLine.text.trim().isEmpty) _addressLine.text = r.addressLine!;")
a("        if (r.city != null && r.city!.isNotEmpty && _city.text.trim().isEmpty) _city.text = r.city!;")
a("        if (r.state != null && r.state!.isNotEmpty && _state.text.trim().isEmpty) _state.text = r.state!;")
a("        if (r.pincode != null && r.pincode!.isNotEmpty && _pincode.text.trim().isEmpty) _pincode.text = r.pincode!;")
a("      });")
a("      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(r.isHighAccuracy ? 'Location detected!' : 'Location detected'), backgroundColor: r.isHighAccuracy ? Colors.green : Colors.orange));")
a("    } catch (e) {")
a("      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Location error: $e')));")
a("    } finally { if (mounted) setState(() => _locating = false); }")
a("  }")
a("")

with open(out, 'w', encoding='utf-8') as f:
    f.write('\n'.join(L))

print("PART1 DONE")
