// Mocks generated by Mockito from annotations
// in hyperlocal_customer_app/test/features/directions/presentation/controllers/directions_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:hyperlocal_app/features/directions/domain/location_service.dart'
    as _i4;
import 'package:hyperlocal_app/features/directions/domain/models/location_models.dart'
    as _i2;
import 'package:hyperlocal_app/features/shop_details/domain/models/shop_details_models.dart'
    as _i3;
import 'package:hyperlocal_app/features/shop_details/domain/shop_details_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCoordinates_0 extends _i1.SmartFake implements _i2.Coordinates {
  _FakeCoordinates_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShopProfile_1 extends _i1.SmartFake implements _i3.ShopProfile {
  _FakeShopProfile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i4.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> isGpsEnabled() => (super.noSuchMethod(
    Invocation.method(#isGpsEnabled, []),
    returnValue: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestPermission() => (super.noSuchMethod(
    Invocation.method(#requestPermission, []),
    returnValue: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.Coordinates> getCurrentLocation() => (super.noSuchMethod(
    Invocation.method(#getCurrentLocation, []),
    returnValue: _i5.Future<_i2.Coordinates>.value(
      _FakeCoordinates_0(this, Invocation.method(#getCurrentLocation, [])),
    ),
  ) as _i5.Future<_i2.Coordinates>);

  @override
  _i5.Future<void> openExternalNavigation(
    _i2.Coordinates? destination,
    String? label,
  ) => (super.noSuchMethod(
    Invocation.method(#openExternalNavigation, [destination, label]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  double calculateDistance(_i2.Coordinates? start, _i2.Coordinates? end) =>
      (super.noSuchMethod(
        Invocation.method(#calculateDistance, [start, end]),
        returnValue: 0.0,
      ) as double);
}

/// A class which mocks [ShopDetailsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopDetailsRepository extends _i1.Mock
    implements _i6.ShopDetailsRepository {
  MockShopDetailsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.ShopProfile> getShopProfile(String? shopId) =>
      (super.noSuchMethod(
        Invocation.method(#getShopProfile, [shopId]),
        returnValue: _i5.Future<_i3.ShopProfile>.value(
          _FakeShopProfile_1(
            this,
            Invocation.method(#getShopProfile, [shopId]),
          ),
        ),
      ) as _i5.Future<_i3.ShopProfile>);

  @override
  _i5.Future<void> toggleSaveShop(String? shopId, bool? save) =>
      (super.noSuchMethod(
        Invocation.method(#toggleSaveShop, [shopId, save]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
