// Mocks generated by Mockito from annotations
// in hyperlocal_app/test/features/directions/presentation/controllers/directions_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:hyperlocal_app/features/directions/domain/location_service.dart'
    as _i5;
import 'package:hyperlocal_app/features/directions/domain/models/location_models.dart'
    as _i2;
import 'package:hyperlocal_app/features/shop_details/domain/models/business_profile_models.dart'
    as _i4;
import 'package:hyperlocal_app/features/shop_details/domain/models/shop_details_models.dart'
    as _i3;
import 'package:hyperlocal_app/features/shop_details/domain/shop_details_repository.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCoordinates_0 extends _i1.SmartFake implements _i2.Coordinates {
  _FakeCoordinates_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShopProfile_1 extends _i1.SmartFake implements _i3.ShopProfile {
  _FakeShopProfile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransportQuoteReceipt_2 extends _i1.SmartFake
    implements _i4.TransportQuoteReceipt {
  _FakeTransportQuoteReceipt_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransportTrips_3 extends _i1.SmartFake
    implements _i4.TransportTrips {
  _FakeTransportTrips_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransportBooking_4 extends _i1.SmartFake
    implements _i4.TransportBooking {
  _FakeTransportBooking_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i5.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> isGpsEnabled() => (super.noSuchMethod(
    Invocation.method(#isGpsEnabled, []),
    returnValue: _i6.Future<bool>.value(false),
  ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> requestPermission() => (super.noSuchMethod(
    Invocation.method(#requestPermission, []),
    returnValue: _i6.Future<bool>.value(false),
  ) as _i6.Future<bool>);

  @override
  _i6.Future<_i2.Coordinates> getCurrentLocation() => (super.noSuchMethod(
    Invocation.method(#getCurrentLocation, []),
    returnValue: _i6.Future<_i2.Coordinates>.value(
      _FakeCoordinates_0(this, Invocation.method(#getCurrentLocation, [])),
    ),
  ) as _i6.Future<_i2.Coordinates>);

  @override
  _i6.Future<void> openExternalNavigation(
    _i2.Coordinates? destination,
    String? label,
  ) => (super.noSuchMethod(
    Invocation.method(#openExternalNavigation, [destination, label]),
    returnValue: _i6.Future<void>.value(),
    returnValueForMissingStub: _i6.Future<void>.value(),
  ) as _i6.Future<void>);

  @override
  double calculateDistance(_i2.Coordinates? start, _i2.Coordinates? end) =>
      (super.noSuchMethod(
        Invocation.method(#calculateDistance, [start, end]),
        returnValue: 0.0,
      ) as double);
}

/// A class which mocks [ShopDetailsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopDetailsRepository extends _i1.Mock
    implements _i7.ShopDetailsRepository {
  MockShopDetailsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.ShopProfile> getShopProfile(String? shopId) =>
      (super.noSuchMethod(
        Invocation.method(#getShopProfile, [shopId]),
        returnValue: _i6.Future<_i3.ShopProfile>.value(
          _FakeShopProfile_1(
            this,
            Invocation.method(#getShopProfile, [shopId]),
          ),
        ),
      ) as _i6.Future<_i3.ShopProfile>);

  @override
  _i6.Future<void> toggleSaveShop(String? shopId, bool? save) =>
      (super.noSuchMethod(
        Invocation.method(#toggleSaveShop, [shopId, save]),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.RestaurantProfile?> getRestaurantProfile(String? shopId) =>
      (super.noSuchMethod(
        Invocation.method(#getRestaurantProfile, [shopId]),
        returnValue: _i6.Future<_i4.RestaurantProfile?>.value(),
      ) as _i6.Future<_i4.RestaurantProfile?>);

  @override
  _i6.Future<_i4.TransportServiceProfile?> getTransportServiceProfile(
    String? shopId,
  ) => (super.noSuchMethod(
    Invocation.method(#getTransportServiceProfile, [shopId]),
    returnValue: _i6.Future<_i4.TransportServiceProfile?>.value(),
  ) as _i6.Future<_i4.TransportServiceProfile?>);

  @override
  _i6.Future<_i4.TransportQuoteReceipt> requestTransportQuote(
    _i4.TransportQuoteRequest? request,
  ) => (super.noSuchMethod(
    Invocation.method(#requestTransportQuote, [request]),
    returnValue: _i6.Future<_i4.TransportQuoteReceipt>.value(
      _FakeTransportQuoteReceipt_2(
        this,
        Invocation.method(#requestTransportQuote, [request]),
      ),
    ),
  ) as _i6.Future<_i4.TransportQuoteReceipt>);

  @override
  _i6.Future<_i4.TransportTrips> getMyTransportTrips() => (super.noSuchMethod(
    Invocation.method(#getMyTransportTrips, []),
    returnValue: _i6.Future<_i4.TransportTrips>.value(
      _FakeTransportTrips_3(this, Invocation.method(#getMyTransportTrips, [])),
    ),
  ) as _i6.Future<_i4.TransportTrips>);

  @override
  _i6.Future<_i4.TransportBooking> acceptTransportQuote(String? quoteId) =>
      (super.noSuchMethod(
        Invocation.method(#acceptTransportQuote, [quoteId]),
        returnValue: _i6.Future<_i4.TransportBooking>.value(
          _FakeTransportBooking_4(
            this,
            Invocation.method(#acceptTransportQuote, [quoteId]),
          ),
        ),
      ) as _i6.Future<_i4.TransportBooking>);

  @override
  _i6.Future<_i4.TransportBooking> cancelTransportBooking(
    String? bookingId, {
    String? reason,
  }) => (super.noSuchMethod(
    Invocation.method(#cancelTransportBooking, [bookingId], {#reason: reason}),
    returnValue: _i6.Future<_i4.TransportBooking>.value(
      _FakeTransportBooking_4(
        this,
        Invocation.method(
          #cancelTransportBooking,
          [bookingId],
          {#reason: reason},
        ),
      ),
    ),
  ) as _i6.Future<_i4.TransportBooking>);
}
