// Mocks generated by Mockito from annotations
// in hyperlocal_customer_app/test/features/location/presentation/controllers/location_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hyperlocal_app/core/storage/secure_storage_service.dart'
    as _i6;
import 'package:hyperlocal_app/features/location/domain/location_repository.dart'
    as _i3;
import 'package:hyperlocal_app/features/location/domain/models/location_permission_status.dart'
    as _i5;
import 'package:hyperlocal_app/features/location/domain/models/user_location.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserLocation_0 extends _i1.SmartFake implements _i2.UserLocation {
  _FakeUserLocation_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i3.LocationRepository {
  MockLocationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> isLocationServiceEnabled() => (super.noSuchMethod(
    Invocation.method(#isLocationServiceEnabled, []),
    returnValue: _i4.Future<bool>.value(false),
  ) as _i4.Future<bool>);

  @override
  _i4.Future<_i5.LocationPermissionStatus> checkPermission() =>
      (super.noSuchMethod(
        Invocation.method(#checkPermission, []),
        returnValue: _i4.Future<_i5.LocationPermissionStatus>.value(
          _i5.LocationPermissionStatus.granted,
        ),
      ) as _i4.Future<_i5.LocationPermissionStatus>);

  @override
  _i4.Future<_i5.LocationPermissionStatus> requestPermission() =>
      (super.noSuchMethod(
        Invocation.method(#requestPermission, []),
        returnValue: _i4.Future<_i5.LocationPermissionStatus>.value(
          _i5.LocationPermissionStatus.granted,
        ),
      ) as _i4.Future<_i5.LocationPermissionStatus>);

  @override
  _i4.Future<_i2.UserLocation> getCurrentLocation() => (super.noSuchMethod(
    Invocation.method(#getCurrentLocation, []),
    returnValue: _i4.Future<_i2.UserLocation>.value(
      _FakeUserLocation_0(this, Invocation.method(#getCurrentLocation, [])),
    ),
  ) as _i4.Future<_i2.UserLocation>);

  @override
  _i4.Future<_i2.UserLocation?> getLastKnownLocation() => (super.noSuchMethod(
    Invocation.method(#getLastKnownLocation, []),
    returnValue: _i4.Future<_i2.UserLocation?>.value(),
  ) as _i4.Future<_i2.UserLocation?>);

  @override
  _i4.Future<void> openLocationSettings() => (super.noSuchMethod(
    Invocation.method(#openLocationSettings, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.UserLocation>> searchManualLocations(String? query) =>
      (super.noSuchMethod(
        Invocation.method(#searchManualLocations, [query]),
        returnValue: _i4.Future<List<_i2.UserLocation>>.value(
          <_i2.UserLocation>[],
        ),
      ) as _i4.Future<List<_i2.UserLocation>>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i6.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveToken(String? token) => (super.noSuchMethod(
    Invocation.method(#saveToken, [token]),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getToken() => (super.noSuchMethod(
    Invocation.method(#getToken, []),
    returnValue: _i4.Future<String?>.value(),
  ) as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteToken() => (super.noSuchMethod(
    Invocation.method(#deleteToken, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveRefreshToken(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(#saveRefreshToken, [refreshToken]),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getRefreshToken() => (super.noSuchMethod(
    Invocation.method(#getRefreshToken, []),
    returnValue: _i4.Future<String?>.value(),
  ) as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteRefreshToken() => (super.noSuchMethod(
    Invocation.method(#deleteRefreshToken, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveSessionId(String? sessionId) => (super.noSuchMethod(
    Invocation.method(#saveSessionId, [sessionId]),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getSessionId() => (super.noSuchMethod(
    Invocation.method(#getSessionId, []),
    returnValue: _i4.Future<String?>.value(),
  ) as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteSessionId() => (super.noSuchMethod(
    Invocation.method(#deleteSessionId, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> setGuestMode(bool? isGuest) => (super.noSuchMethod(
    Invocation.method(#setGuestMode, [isGuest]),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isGuestMode() => (super.noSuchMethod(
    Invocation.method(#isGuestMode, []),
    returnValue: _i4.Future<bool>.value(false),
  ) as _i4.Future<bool>);

  @override
  _i4.Future<void> saveDeviceId(String? deviceId) => (super.noSuchMethod(
    Invocation.method(#saveDeviceId, [deviceId]),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getDeviceId() => (super.noSuchMethod(
    Invocation.method(#getDeviceId, []),
    returnValue: _i4.Future<String?>.value(),
  ) as _i4.Future<String?>);

  @override
  _i4.Future<void> write({required String? key, required String? value}) =>
      (super.noSuchMethod(
        Invocation.method(#write, [], {#key: key, #value: value}),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> read({required String? key}) => (super.noSuchMethod(
    Invocation.method(#read, [], {#key: key}),
    returnValue: _i4.Future<String?>.value(),
  ) as _i4.Future<String?>);

  @override
  _i4.Future<void> delete({required String? key}) => (super.noSuchMethod(
    Invocation.method(#delete, [], {#key: key}),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
    Invocation.method(#clearAll, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);
}
