"""OTP storage abstraction â€” swappable in-memory / Redis backends.

The OTP service (:mod:`app.services.otp_service`) is hot-path code used by
both the customer and shopkeeper auth flows. Storing OTP records in a
per-process dict breaks the moment the API runs with 2+ workers or
instances (the OTP is generated by worker A but verified by worker B).

Backends:
    memory://                       â†’ InMemoryOTPStore (dev/test, single process)
    redis://host:port/db            â†’ RedisOTPStore  (production, distributed)

Redis semantics used here:
    * ``SETEX`` with a TTL equal to the OTP expiry â€” expired OTPs vanish
      automatically, no background sweeper needed.
    * JSON-encoded record payloads (OTP hash + salt never leave the store
      in raw form; hashing stays in the service layer).
    * Keys are namespaced under ``otp:`` to co-exist with the cache
      (db 0), Celery (db 1-2), and rate-limit (db 3) users.
"""

import json
from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any, Optional

from app.core.exceptions import ServiceUnavailableError
from app.core.logging import get_logger
from app.core.redis import client_options

logger = get_logger("app.services.otp_store")

# Keys of a record that hold datetimes and must survive (de)serialization.
_DATETIME_KEYS = ("expires_at", "last_resend_at", "created_at")

KEY_PREFIX = "otp:"


class OTPStorageUnavailableError(ServiceUnavailableError):
    """Redis-backed OTP store unreachable â€” authentication must fail closed.

    Raised as a 503 so clients see an explicit, retryable outage instead of a
    hang, a 500, or (worse) a permissive auth path.
    """

    def __init__(self, message: str = "OTP service temporarily unavailable"):
        super().__init__(message)


class BaseOTPStore(ABC):
    """Minimal key/value interface the OTP service needs."""

    name: str = "base"

    @abstractmethod
    def get(self, phone: str) -> Optional[dict[str, Any]]:
        """Return the OTP record for ``phone`` or ``None``."""

    @abstractmethod
    def set(self, phone: str, record: dict[str, Any], ttl_seconds: int) -> None:
        """Store ``record`` for ``phone``, auto-expiring after ``ttl_seconds``."""

    @abstractmethod
    def pop(self, phone: str) -> None:
        """Remove the record for ``phone`` if present (single-use / invalidate)."""

    @abstractmethod
    def clear_all(self) -> None:
        """Remove every OTP record (ops reset / test isolation)."""


# â”€â”€ Serialization helpers (shared by the Redis backend) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

def _serialize(record: dict[str, Any]) -> str:
    payload: dict[str, Any] = {}
    for key, value in record.items():
        payload[key] = value.isoformat() if isinstance(value, datetime) else value
    return json.dumps(payload)


def _deserialize(raw: str) -> dict:
    payload = json.loads(raw)
    for key in _DATETIME_KEYS:
        if key in payload and isinstance(payload[key], str):
            payload[key] = datetime.fromisoformat(payload[key])
    return payload


class InMemoryOTPStore(BaseOTPStore):
    """Process-local dict â€” single-worker dev/test only (parity with legacy)."""

    name = "memory"

    def __init__(self) -> None:
        self._store: dict[str, dict] = {}

    def get(self, phone: str) -> Optional[dict[str, Any]]:
        return self._store.get(phone)

    def set(self, phone: str, record: dict[str, Any], ttl_seconds: int) -> None:
        # TTL is advisory here; the service layer already enforces expiry via
        # the ``expires_at`` comparison, so single-process behavior is exact.
        self._store[phone] = record

    def pop(self, phone: str) -> None:
        self._store.pop(phone, None)

    def clear_all(self) -> None:
        self._store.clear()


class RedisOTPStore(BaseOTPStore):
    """Distributed store backed by Redis (sync client â€” mirrors the sync DB
    access pattern already accepted across the codebase).

    Phase 6 â€” graceful failure: when Redis is unreachable every operation
    raises :class:`OTPStorageUnavailableError` (a 503 ``ServiceUnavailableError``)
    instead of an unbranded connection exception. OTPs must FAIL CLOSED
    (never authenticate outside the store), so callers get an explicit
    "temporarily unavailable" instead of a hang, a 500, or a false deny.
    """

    name = "redis"

    def __init__(self, uri: str, client: Any = None) -> None:
        # ``client`` is injectable for tests; production builds one from the URI
        # using the shared hardened options (timeout/retry/health) from
        # app.core.redis so behaviour matches the cache and rate limiter.
        if client is not None:
            self._client = client
        else:
            import redis as redis_sync  # noqa: PLC0415

            self._client = redis_sync.Redis.from_url(uri, **client_options())

    def get(self, phone: str) -> Optional[dict[str, Any]]:
        try:
            raw = self._client.get(KEY_PREFIX + phone)
        except Exception as exc:  # noqa: BLE001 â€” Redis outage â†’ controlled 503
            logger.error("Redis OTP get failed for %s: %s", phone, exc)
            raise OTPStorageUnavailableError() from exc
        if raw is None:
            return None
        return _deserialize(raw)

    def set(self, phone: str, record: dict[str, Any], ttl_seconds: int) -> None:
        ttl = max(1, int(ttl_seconds))
        try:
            self._client.setex(KEY_PREFIX + phone, ttl, _serialize(record))
        except Exception as exc:  # noqa: BLE001
            logger.error("Redis OTP set failed for %s: %s", phone, exc)
            raise OTPStorageUnavailableError() from exc

    def pop(self, phone: str) -> None:
        try:
            self._client.delete(KEY_PREFIX + phone)
        except Exception as exc:  # noqa: BLE001
            logger.error("Redis OTP delete failed for %s: %s", phone, exc)
            raise OTPStorageUnavailableError() from exc

    def clear_all(self) -> None:
        try:
            keys = list(self._client.scan_iter(match=KEY_PREFIX + "*"))
            if keys:
                self._client.delete(*keys)
        except Exception as exc:  # noqa: BLE001
            logger.error("Redis OTP clear_all failed: %s", exc)
            raise OTPStorageUnavailableError() from exc


# â”€â”€ Factory / module-level singleton â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

_active_store: Optional[BaseOTPStore] = None
_active_uri: Optional[str] = None


def create_otp_store(uri: str) -> BaseOTPStore:
    """Build a store from a storage URI (``memory://`` or ``redis://...``)."""
    scheme = uri.split(":", 1)[0].lower()
    if scheme == "memory":
        store: BaseOTPStore = InMemoryOTPStore()
    elif scheme == "redis":
        store = RedisOTPStore(uri)
    else:
        raise ValueError(
            f"Unsupported OTP_STORAGE_URI scheme '{scheme}://' â€” "
            "use 'memory://' or 'redis://host:port/db'"
        )
    logger.info("OTP store initialised: %s (%s)", store.name, uri)
    return store


def get_otp_store(uri: str) -> BaseOTPStore:
    """Return a cached store for ``uri``; rebuilds if the URI changed.

    Caching on the URI (rather than unconditionally) lets tests flip
    ``settings.OTP_STORAGE_URI`` at runtime and get the right backend.
    """
    global _active_store, _active_uri
    if _active_store is None or _active_uri != uri:
        _active_store = create_otp_store(uri)
        _active_uri = uri
    return _active_store


def reset_otp_store() -> None:
    """Drop the cached singleton (test isolation helper)."""
    global _active_store, _active_uri
    _active_store = None
    _active_uri = None
