"""OTP storage abstraction — swappable in-memory / Redis backends.

The OTP service (:mod:`app.services.otp_service`) is hot-path code used by
both the customer and shopkeeper auth flows. Storing OTP records in a
per-process dict breaks the moment the API runs with 2+ workers or
instances (the OTP is generated by worker A but verified by worker B).

Backends:
    memory://                       → InMemoryOTPStore (dev/test, single process)
    redis://host:port/db            → RedisOTPStore  (production, distributed)

Redis semantics used here:
    * ``SETEX`` with a TTL equal to the OTP expiry — expired OTPs vanish
      automatically, no background sweeper needed.
    * JSON-encoded record payloads (OTP hash + salt never leave the store
      in raw form; hashing stays in the service layer).
    * Keys are namespaced under ``otp:`` to co-exist with the cache
      (db 0), Celery (db 1-2), and rate-limit (db 3) users.
"""

import json
from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any, Optional

from app.core.logging import get_logger

logger = get_logger("app.services.otp_store")

# Keys of a record that hold datetimes and must survive (de)serialization.
_DATETIME_KEYS = ("expires_at", "last_resend_at", "created_at")

KEY_PREFIX = "otp:"


class BaseOTPStore(ABC):
    """Minimal key/value interface the OTP service needs."""

    name: str = "base"

    @abstractmethod
    def get(self, phone: str) -> Optional[dict]:
        """Return the OTP record for ``phone`` or ``None``."""

    @abstractmethod
    def set(self, phone: str, record: dict, ttl_seconds: int) -> None:
        """Store ``record`` for ``phone``, auto-expiring after ``ttl_seconds``."""

    @abstractmethod
    def pop(self, phone: str) -> None:
        """Remove the record for ``phone`` if present (single-use / invalidate)."""

    @abstractmethod
    def clear_all(self) -> None:
        """Remove every OTP record (ops reset / test isolation)."""


# ── Serialization helpers (shared by the Redis backend) ──────────────────────

def _serialize(record: dict) -> str:
    payload: dict[str, Any] = {}
    for key, value in record.items():
        payload[key] = value.isoformat() if isinstance(value, datetime) else value
    return json.dumps(payload)


def _deserialize(raw: str) -> dict:
    payload = json.loads(raw)
    for key in _DATETIME_KEYS:
        if key in payload and isinstance(payload[key], str):
            payload[key] = datetime.fromisoformat(payload[key])
    return payload


class InMemoryOTPStore(BaseOTPStore):
    """Process-local dict — single-worker dev/test only (parity with legacy)."""

    name = "memory"

    def __init__(self) -> None:
        self._store: dict[str, dict] = {}

    def get(self, phone: str) -> Optional[dict]:
        return self._store.get(phone)

    def set(self, phone: str, record: dict, ttl_seconds: int) -> None:
        # TTL is advisory here; the service layer already enforces expiry via
        # the ``expires_at`` comparison, so single-process behavior is exact.
        self._store[phone] = record

    def pop(self, phone: str) -> None:
        self._store.pop(phone, None)

    def clear_all(self) -> None:
        self._store.clear()


class RedisOTPStore(BaseOTPStore):
    """Distributed store backed by Redis (sync client — mirrors the sync DB
    access pattern already accepted across the codebase)."""

    name = "redis"

    def __init__(self, uri: str, client: Any = None) -> None:
        # ``client`` is injectable for tests; production builds one from the URI.
        if client is not None:
            self._client = client
        else:
            import redis as redis_sync

            self._client = redis_sync.Redis.from_url(
                uri,
                decode_responses=True,
                socket_connect_timeout=2,
                socket_timeout=2,
            )

    def get(self, phone: str) -> Optional[dict]:
        raw = self._client.get(KEY_PREFIX + phone)
        if raw is None:
            return None
        return _deserialize(raw)

    def set(self, phone: str, record: dict, ttl_seconds: int) -> None:
        ttl = max(1, int(ttl_seconds))
        self._client.setex(KEY_PREFIX + phone, ttl, _serialize(record))

    def pop(self, phone: str) -> None:
        self._client.delete(KEY_PREFIX + phone)

    def clear_all(self) -> None:
        keys = list(self._client.scan_iter(match=KEY_PREFIX + "*"))
        if keys:
            self._client.delete(*keys)


# ── Factory / module-level singleton ─────────────────────────────────────────

_active_store: Optional[BaseOTPStore] = None
_active_uri: Optional[str] = None


def create_otp_store(uri: str) -> BaseOTPStore:
    """Build a store from a storage URI (``memory://`` or ``redis://...``)."""
    scheme = uri.split(":", 1)[0].lower()
    if scheme == "memory":
        store: BaseOTPStore = InMemoryOTPStore()
    elif scheme == "redis":
        store = RedisOTPStore(uri)
    else:
        raise ValueError(
            f"Unsupported OTP_STORAGE_URI scheme '{scheme}://' — "
            "use 'memory://' or 'redis://host:port/db'"
        )
    logger.info("OTP store initialised: %s (%s)", store.name, uri)
    return store


def get_otp_store(uri: str) -> BaseOTPStore:
    """Return a cached store for ``uri``; rebuilds if the URI changed.

    Caching on the URI (rather than unconditionally) lets tests flip
    ``settings.OTP_STORAGE_URI`` at runtime and get the right backend.
    """
    global _active_store, _active_uri
    if _active_store is None or _active_uri != uri:
        _active_store = create_otp_store(uri)
        _active_uri = uri
    return _active_store


def reset_otp_store() -> None:
    """Drop the cached singleton (test isolation helper)."""
    global _active_store, _active_uri
    _active_store = None
    _active_uri = None
