// Mocks generated by Mockito from annotations
// in hyperlocal_customer_app/test/features/auth/presentation/controllers/auth_controller_test.dart.
// Do not manually edit this file — regenerate via `dart run build_runner build`.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hyperlocal_customer_app/core/storage/secure_storage_service.dart'
    as _i5;
import 'package:hyperlocal_customer_app/features/auth/domain/auth_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> sendOtp(String? phoneNumber) => (super.noSuchMethod(
    Invocation.method(#sendOtp, [phoneNumber]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.AuthResult> verifyOtp({
    required String? phoneNumber,
    required String? otpCode,
    String? deviceId,
    String? deviceName,
    String? deviceType,
    String? appVersion,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#verifyOtp, [], {
          #phoneNumber: phoneNumber,
          #otpCode: otpCode,
          #deviceId: deviceId,
          #deviceName: deviceName,
          #deviceType: deviceType,
          #appVersion: appVersion,
        }),
        returnValue: _i3.Future<_i2.AuthResult>.value(
          _i4.dummyValue<_i2.AuthResult>(
            this,
            Invocation.method(#verifyOtp, [], {
              #phoneNumber: phoneNumber,
              #otpCode: otpCode,
            }),
          ),
        ),
      ) as _i3.Future<_i2.AuthResult>);

  @override
  _i3.Future<String?> refreshToken(String? refreshToken, {String? deviceId}) =>
      (super.noSuchMethod(
        Invocation.method(#refreshToken, [refreshToken], {#deviceId: deviceId}),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> logout({
    String? refreshToken,
    String? sessionId,
    bool revokeAll = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#logout, [], {
          #refreshToken: refreshToken,
          #sessionId: sessionId,
          #revokeAll: revokeAll,
        }),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i5.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveToken(String? token) => (super.noSuchMethod(
    Invocation.method(#saveToken, [token]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getToken() => (super.noSuchMethod(
    Invocation.method(#getToken, []),
    returnValue: _i3.Future<String?>.value(),
  ) as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteToken() => (super.noSuchMethod(
    Invocation.method(#deleteToken, []),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveRefreshToken(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(#saveRefreshToken, [refreshToken]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getRefreshToken() => (super.noSuchMethod(
    Invocation.method(#getRefreshToken, []),
    returnValue: _i3.Future<String?>.value(),
  ) as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteRefreshToken() => (super.noSuchMethod(
    Invocation.method(#deleteRefreshToken, []),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveSessionId(String? sessionId) => (super.noSuchMethod(
    Invocation.method(#saveSessionId, [sessionId]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getSessionId() => (super.noSuchMethod(
    Invocation.method(#getSessionId, []),
    returnValue: _i3.Future<String?>.value(),
  ) as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteSessionId() => (super.noSuchMethod(
    Invocation.method(#deleteSessionId, []),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> setGuestMode(bool? isGuest) => (super.noSuchMethod(
    Invocation.method(#setGuestMode, [isGuest]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isGuestMode() => (super.noSuchMethod(
    Invocation.method(#isGuestMode, []),
    returnValue: _i3.Future<bool>.value(false),
  ) as _i3.Future<bool>);

  @override
  _i3.Future<void> saveDeviceId(String? deviceId) => (super.noSuchMethod(
    Invocation.method(#saveDeviceId, [deviceId]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getDeviceId() => (super.noSuchMethod(
    Invocation.method(#getDeviceId, []),
    returnValue: _i3.Future<String?>.value(),
  ) as _i3.Future<String?>);

  @override
  _i3.Future<void> write({required String? key, required String? value}) =>
      (super.noSuchMethod(
        Invocation.method(#write, [], {#key: key, #value: value}),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> read({required String? key}) => (super.noSuchMethod(
    Invocation.method(#read, [], {#key: key}),
    returnValue: _i3.Future<String?>.value(),
  ) as _i3.Future<String?>);

  @override
  _i3.Future<void> delete({required String? key}) => (super.noSuchMethod(
    Invocation.method(#delete, [], {#key: key}),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
    Invocation.method(#clearAll, []),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);
}