// Mocks generated by Mockito from annotations
// in hyperlocal_customer_app/test/features/product_details/presentation/controllers/product_details_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hyperlocal_app/features/product_details/domain/models/product_details_models.dart'
    as _i2;
import 'package:hyperlocal_app/features/product_details/domain/product_details_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProductDetails_0 extends _i1.SmartFake
    implements _i2.ProductDetails {
  _FakeProductDetails_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductDetailsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductDetailsRepository extends _i1.Mock
    implements _i3.ProductDetailsRepository {
  MockProductDetailsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProductDetails> getProductDetails(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(#getProductDetails, [productId]),
        returnValue: _i4.Future<_i2.ProductDetails>.value(
          _FakeProductDetails_0(
            this,
            Invocation.method(#getProductDetails, [productId]),
          ),
        ),
      ) as _i4.Future<_i2.ProductDetails>);

  @override
  _i4.Future<void> toggleSaveProduct(String? productId, bool? save) =>
      (super.noSuchMethod(
        Invocation.method(#toggleSaveProduct, [productId, save]),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
