import 'package:flutter_test/flutter_test.dart';
import 'package:hyperlocal_app/features/search/data/api_search_repository.dart';
import 'package:mockito/mockito.dart';

// `MockApiClient` is generated by the saved-and-history data test's
// `@GenerateMocks([ApiClient])`. Reusing it rather than declaring a second
// `@GenerateMocks` here means adding this file needs no `build_runner` pass, so
// the suite stays runnable with `flutter test` alone.
import '../../saved_and_history/data/api_saved_and_history_repository_test.mocks.dart';

void main() {
  late MockApiClient api;
  late ApiSearchRepository repository;

  setUp(() {
    api = MockApiClient();
    repository = ApiSearchRepository(api);
  });

  void respondWith(Object? payload) {
    when(
      api.get(
        any,
        queryParameters: anyNamed('queryParameters'),
        requiresAuth: anyNamed('requiresAuth'),
      ),
    ).thenAnswer((_) async => payload);
  }

  group('getRecentSearches reads the ACCOUNT history', () {
    test('returns the queries the server sent, in server order', () async {
      respondWith([
        {'query': 'dove shampoo', 'result_count': 4},
        {'query': 'bosch drill', 'result_count': 2},
      ]);

      expect(await repository.getRecentSearches(), [
        'dove shampoo',
        'bosch drill',
      ]);
    });

    test('collapses repeats, because one search is one recent search', () async {
      // The backend may legitimately return the same query twice (the customer
      // searched it again). Two identical rows in a suggestion list is a bug the
      // customer can see.
      respondWith([
        {'query': 'paracetamol'},
        {'query': 'paracetamol'},
        {'query': 'dettol'},
      ]);

      expect(await repository.getRecentSearches(), ['paracetamol', 'dettol']);
    });

    test('tolerates a bare-string row and drops blank ones', () async {
      respondWith(['earbuds', '', '  ', 'ceiling fan']);

      expect(await repository.getRecentSearches(), ['earbuds', 'ceiling fan']);
    });

    test(
      'an unrecognised payload shape yields no history, never a crash',
      () async {
        // History is a convenience list; a shape this build cannot read must
        // degrade to "nothing to suggest" rather than take down the screen.
        respondWith({'unexpected': 'object'});

        expect(await repository.getRecentSearches(), isEmpty);
      },
    );

    test('a failed read yields no history rather than throwing', () async {
      // The device store is the app's real source of recent searches, so a
      // server failure here must not surface as an error the customer sees.
      when(
        api.get(
          any,
          queryParameters: anyNamed('queryParameters'),
          requiresAuth: anyNamed('requiresAuth'),
        ),
      ).thenThrow(Exception('offline'));

      expect(await repository.getRecentSearches(), isEmpty);
    });
  });
}
